---
title: "benchmark-downsample"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(here)
library(tidyverse)
library(Biostrings)
library(data.table)
library(gt)
theme_set(theme_bw())
```

```{r echo=FALSE, message=FALSE}
read.tb <- function(path, method) {
  files <- list.files(path, full.names = TRUE, pattern = 'quality.csv', recursive = TRUE)
  tb <- map_dfr(files, function(x) {data.frame(fread(x))})
  return(tb)
}
```

After synteny with P.effusa, we have new assembly files where some of the contigs are glued. Let's check their qualities.

```{r echo=FALSE}
downsample <- fread('~/project_data/downy/benchmarking/MSU1_downsample/quality/quality_final.csv') |> mutate(method = 'downsample')
not.downsample <- fread('~/project_data/downy/benchmarking/MSU1_no-downsample/quality/quality_final.csv') |> mutate(method = 'downsample')
```


```{r echo=FALSE}
read.length <- c("/home5/yyang55/project_data/downy/benchmarking/MSU1_downsample/Quesada_SQIIe_MSU1.fasta.gz",
                 "/home5/yyang55/project_data/downy/benchmarking/MSU1_no-downsample/Quesada_SQIIe_MSU1.fasta.gz") |> 
  map_dfr(function(file) {
    seq <- readDNAStringSet(file)
    data.frame(method = basename(dirname(file)),
               contig = names(seq),
               length = width(seq))
    }) |> group_by(method) |> 
  arrange(desc(length)) |>
  top_n(30) |> 
  mutate(rank = 1:n()) |> 
  ungroup()

ggplot(read.length, aes(x = factor(rank), y = length)) +
  geom_col() +
  scale_y_continuous(labels = scales::label_number(big.mark = ",")) +
  facet_wrap(~method, scales = 'free_y', ncol = 1) +
  labs(
    title = "Top 30 Longest Contigs",
    subtitle = "Ordered by length",
    x = "Rank",
    y = "Length (bp)"
  )
```