---
title: "unplace-contigs"
output:
  html_document: default
---

```{r message=FALSE, echo=FALSE}
library(Biostrings)
library(tidyverse)
library(gt)
library(here)
```

# mitochondria

```{r echo=FALSE}
blast.tb <- list.files('~/project_data/downy/BLAST-asm',
                       pattern = '.mito.tsv', full.names = TRUE) |> 
  map_dfr(function(file) {
    read.table(file, colClasses = c('character')) |> mutate(sample = str_remove(basename(file), '.mito.tsv'))
  })
blast.mito <- blast.tb |>
  transmute(
    sample = sample,
    seqid = V1,
    pident = V3,
    align.length = V4,
    query.length = V5,
    query.start = V6,
    query.end = V7,
    subject.length = V8,
    subject.start = V9,
    subject.end = V10,
    e.value = V11
  ) |>
  mutate(across(-c(sample, seqid), \(x) type.convert(x, as.is = TRUE))) |> 
  mutate(`align/query` = round(align.length/query.length, 3))

blast.mito |> 
  group_by(sample) |> 
  arrange(desc(`align/query`), desc(align.length), .by_group = TRUE) |> 
  gt() 
```

# Clean up unplaced contigs from assemblies.

Some unplaced contigs are mapped to the mitochondrial genome.

```{r}
unplaced.exclude <- blast.mito |> 
  filter(e.value == 0 & `align/query` >= 0.5) # remove contigs that aligned to mito genome under these threshold
unplaced.exclude |> 
  group_by(sample) |> 
  arrange(desc(`align/query`), desc(align.length), .by_group = TRUE) |> 
  gt() 
```

```{r}
library(fs)
files <- dir_ls('~/project_data/downy/Assembly/', glob = "*/*.fasta.gz", recurse = 1)
for (file in files) {
  data <- readDNAStringSet(file)
  # get mito exclude list
  contigs.exclude <- filter(unplaced.exclude, sample == str_remove(basename(file),'.fasta.gz'))$seqid
  # create dir
  dir.create(path.clean <- file.path('~/project_data/downy/cleaned_contigs/', str_remove(basename(file),'.fasta.gz')),
             recursive = TRUE, showWarnings = FALSE)
  dir.create(path.mito <- file.path('~/project_data/downy/mitochondrial_contigs/', str_remove(basename(file),'.fasta.gz')),
             recursive = TRUE, showWarnings = FALSE)
  # write fasta
  writeXStringSet(data[!(names(data) %in% contigs.exclude)], 
                  file.path(path.clean, basename(file)), compress = TRUE)
  writeXStringSet(data[(names(data) %in% contigs.exclude)], 
                  file.path(path.mito, basename(file)), compress = TRUE)
}
```
