---
title: "test"
author: "Yixuan Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(GENESPACE)
library(here)
library(data.table)
library(tidyverse)
library(Biostrings)
library(gt)
```

# Set Up

```{r echo=FALSE}
genomeRepo <- "~/project_data/downy/genespace/genomes/"
wd <- "~/project_data/downy/genespace/"
path2mcscanx <- "/Users/yixuanyang/miniforge3/bin/"
```

parse annotation

```{r echo=FALSE}
genomes2run <- c("Peronospora_effusa", "Bremia_lactucae", "Phytophthora_sojae")
parsedPaths <- parse_annotations(
  rawGenomeRepo = genomeRepo,
  genomeDirs = genomes2run,
  genomeIDs = genomes2run,
  headerSep = NA,
  headerEntryIndex = 1,
  genespaceWd = wd)
asm2run <- c("Quesada_SQIIe_MSU1", "Quesada_SQIIe_SC1982", "Quesada_SQIIe_Phumuli")
parsedPaths <- parse_annotations(
  rawGenomeRepo = genomeRepo,
  genomeDirs = asm2run,
  genomeIDs = asm2run,
  headerSep = NA,
  headerEntryIndex = 1,
  gffIdColumn = "ID",
  genespaceWd = wd)
```

# Run Genespace

initialize

```{r message=FALSE, echo=FALSE, results=FALSE}
gpar <- init_genespace(
  wd = wd,
  nCores = 10,
  dotplots = 'never',
  path2mcscanx = path2mcscanx)

out <- run_genespace(gpar)
```

```{bash eval=FALSE}
orthofinder -f /Users/yixuanyang/project_data/downy/genespace//tmp -t 10 -a 1 -X -o /Users/yixuanyang/project_data/downy/genespace//orthofinder
```


# Ripanrian plots

```{r echo=FALSE}
for (asm in asm2run){
  plot_riparian(
    gsParam = out,
    genomeIDs = c(asm, genomes2run),
    refGenome = "Peronospora_effusa",
    chrLabFontSize = 2,
    useRegions = FALSE)
}
```

# Number of Chromosomes

```{r echo=FALSE}
syntenicRegion <- file.path(wd, 'results','syntenicRegion_coordinates.csv') |> 
  fread() |> filter((genome1 %in% asm2run)& genome2 == "Peronospora_effusa") |>
  group_by(genome1)

syntenicRegion |>
  summarise(unique_chr_count = n_distinct(chr1)) |> 
  gt()
```

# Glue syntenic contigs together

Prepare syntenic and sequence data.

```{r}
syntenic.list <- syntenicRegion |> 
  group_split() |> 
  lapply(function(x) {
    x |> group_by(chr2) |> arrange(str_rank(chr2, numeric = TRUE))
  })

asm.files <- list.files('~/project_data/downy/hifiasm/fcs-gx/purge_dups', full.names = TRUE, pattern = '.fasta.gz') |> 
  str_sort() |> 
  lapply(function(file) {readDNAStringSet(file)})
```

Below is a function that glues all syntenic contigs and also keep other non-cds contigs

```{r}
glue.contigs <- function(syntenic, asm) {
  new_chromosomes <- DNAStringSet()
  # Glue contigs based on the synteny map 
  # here we assume chr1 is isolate contig name, and chr2 is the ref genome contig name
  for (chr in unique(syntenic$chr2)) {
    df <- syntenic |> filter(chr2 == chr)
    current_chr_contigs <- DNAStringSet()
    for(i in 1:nrow(df)){
      contig_name <- df$chr1[i] 
      sequence <- asm[contig_name]
      if (df$orient[i] == '+') {
        current_chr_contigs <- c(current_chr_contigs, sequence)
      } else { # match orientation
        current_chr_contigs <- c(current_chr_contigs, reverseComplement(sequence))
      }
    }
    glued_sequence <- unlist(current_chr_contigs)
    new_chromosomes <- c(new_chromosomes, DNAStringSet(glued_sequence))
  }
  names(new_chromosomes) <- paste0('glued_', seq_along(new_chromosomes))
  
  # for contigs without cds region, we directly add them to the new asm
  unused_contig_names <- setdiff(names(asm), unique(syntenic$chr1))

  final_assembly <- c(new_chromosomes, asm[unused_contig_names])
  return(final_assembly)
}
```

Glue contigs and save as new asm file for each isolates

```{r}
path <- '~/project_data/downy/hifiasm/fcs-gx/purge_dups/glued'
dir.create(path, showWarnings = FALSE)
MSU1 <- glue.contigs(syntenic.list[[1]], asm.files[[1]])
writeXStringSet(MSU1, file.path(path, 'Quesada_SQIIe_MSU1.fasta.gz'), compress = TRUE)

Phumuli <- glue.contigs(syntenic.list[[2]], asm.files[[2]])
writeXStringSet(Phumuli, file.path(path, 'Quesada_SQIIe_Phumili.fasta.gz'), compress = TRUE)

SC1982 <- glue.contigs(syntenic.list[[3]], asm.files[[3]])
writeXStringSet(SC1982, file.path(path, 'Quesada_SQIIe_SC1982.fasta.gz'), compress = TRUE)
```











