---
title: "Read Distribution"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(tidyverse)
library(data.table)
library(gt)
library(here)
library(taxizedb)
theme_set(theme_bw())
```

# Read distribution 

## Downy Mildew

```{r echo=FALSE}
# child ids under oomycota: 4762
child.id <- c(taxizedb::downstream(4762)$`4762`$childtaxa_id, '4762')

files <- list.files('~/project_data/downy/result/kraken2-asm-fcs/oomycota-genomic/0',
                    full.names = TRUE, recursive = TRUE, pattern = '.kraken$')
df <- map_dfr(files, function(file) {
  data <- fread(file, drop = 5)
  colnames(data) <- c('status', 'id', 'tax', 'length')
  data <- data %>% mutate(file = str_remove(basename(file), '.kraken'))
}) %>% mutate(is.oomycota = (tax %in% child.id))

ggplot(df) +
  geom_histogram(aes(x = length, fill = is.oomycota), binwidth = 1000) +
  scale_y_continuous(labels = scales::label_comma()) +
  facet_wrap(~file, ncol = 1, scales = 'free_y')
```

# P.effusa

```{r echo=FALSE}
files.eff <- list.files('~/project_data/downy/result/verification/length/',
                    full.names = TRUE, recursive = TRUE, pattern = '.kraken$')
df.eff <- map_dfr(files.eff, function(file) {
  data <- fread(file, drop = 5, showProgress = FALSE)
  colnames(data) <- c('status', 'id', 'tax', 'length')
  data <- data %>% mutate(file = str_remove(basename(file), '.kraken'))
}) %>% mutate(is.oomycota = (tax %in% child.id))

ggplot(df.eff) +
  geom_histogram(aes(x = length, fill = is.oomycota), binwidth = 1000) +
  scale_y_continuous(labels = scales::label_comma()) +
  facet_wrap(~file, ncol = 1, scales = 'free_y')
```


# Summary statistics

## Downy Mildew

```{r echo=FALSE}
df %>%
  group_by(file) %>% 
  summarise(min = min(length),
            median = median(length),
            mean = mean(length),
            sd = sd(length),
            max = max(length)) %>% 
  gt %>% fmt_auto()
# oomycota
df %>%
  group_by(file) %>% 
  filter(is.oomycota) %>% 
  summarise(min = min(length),
            median = median(length),
            mean = mean(length),
            sd = sd(length),
            max = max(length)) %>% 
  gt %>% fmt_auto()
```


# P.effusa

```{r echo=FALSE}
df.eff %>%
  group_by(file) %>% 
  summarise(min = min(length),
            median = median(length),
            mean = mean(length),
            sd = sd(length),
            max = max(length)) %>% 
  gt %>% fmt_auto()
# oomycota
df.eff %>%
  group_by(file) %>% 
  filter(is.oomycota) %>% 
  summarise(min = min(length),
            median = median(length),
            mean = mean(length),
            sd = sd(length),
            max = max(length)) %>% 
  gt %>% fmt_auto()
```

# Contig Length Distribution

## contig length distribution with FCS

```{r echo=FALSE}
# contig length distribution using FCS

files <- list.files('~/project_data/downy/GSL_Data/length/fcs',
                    full.names = TRUE, recursive = TRUE, pattern = '.tsv.gz')
df <- map_dfr(files, function(file) {
  data <- fread(file, nThread = 20)
  colnames(data) <- c('id', 'length')
  data <- data %>% mutate(file = str_remove(basename(file), '.tsv.gz'))
})

ggplot(df) +
  geom_histogram(aes(x = length), binwidth = 1000) +
  scale_y_continuous(labels = scales::label_comma()) +
  facet_wrap(~file, ncol = 1, scales = 'free')
```

Summary statistics

```{r echo=FALSE}
df %>%
  group_by(file) %>% 
  summarise(min = min(length),
            median = median(length),
            mean = mean(length),
            sd = sd(length),
            max = max(length)) %>% 
  gt %>% fmt_auto()
```

## contig length distribution with FCS and verified with Kraken2

```{r echo=FALSE}
files <- list.files('~/project_data/downy/GSL_Data/length/kraken',
                    full.names = TRUE, recursive = TRUE, pattern = '.tsv.gz')
df <- map_dfr(files, function(file) {
  data <- fread(file, nThread = 20)
  colnames(data) <- c('id', 'length')
  data <- data %>% mutate(file = str_remove(basename(file), '.tsv.gz'))
})

ggplot(df) +
  geom_histogram(aes(x = length), binwidth = 1000) +
  scale_y_continuous(labels = scales::label_comma()) +
  facet_wrap(~file, ncol = 1, scales = 'free')
```

Summary statistics

```{r echo=FALSE}
df %>%
  group_by(file) %>% 
  summarise(min = min(length),
            median = median(length),
            mean = mean(length),
            sd = sd(length),
            max = max(length)) %>% 
  gt %>% fmt_auto()
```
