---
title: "busco-analysis-refseq"
author: "Yixuan Yang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, echo=FALSE}
library(tidyverse)
library(gt)
library(data.table)
```

# COMPLEASM results

```{r echo=FALSE}
path <- '~/project_data/downy/oomycota-genome/compleasm/'
read.tb <- function(path, method) {
  if (!dir.exists(path)) {
    return(tibble())
  }
  files <- list.files(path, full.names = TRUE, pattern = 'stram.csv')
  if (length(files) == 0) {
    return(tibble())
  }
  tb <- map_dfr(files, function(x) {data.frame(method = method,
                                               sample = str_remove(basename(x), '_stram.csv'),
                                               fread(x))})
  return(tb)
}
```

## stramenopiles_odb10

```{r echo=FALSE}
tb <- read.tb(path, '') %>% select(-any_of("method"))
if (nrow(tb) == 0) {
  "No Compleasm stramenopiles_odb10 result files found."
} else {
  tb %>% gt() %>% fmt_number()
}
```
