---
title: "result"
output: html_document
---

```{r message=FALSE}
rm(list = ls())
library(tidyverse)
library(data.table)
library(openxlsx)
library(here)
library(gt)
```

```{r echo=FALSE}
path <- '~/project_data/downy/result'
data <- list.files(path, pattern = 'csv', full.names = TRUE, recursive = TRUE) %>% 
  map_dfr(function(x) {
    data <- fread(x, header = TRUE, sep = ',') %>% as.data.frame()
    info <- str_split(x, '/')[[1]]
    data$sample <- tail(info,1)[1] %>% str_replace('.csv', '')
    data$confidence.score <- tail(info,2)[1]
    data$data.base <- tail(info,3)[1]
    data$method <- tail(info,4)[1]
    data <- data %>%
      separate(sample, into = c('sample','tool'), sep = '\\.') %>% 
      separate(tool, into = c('tool', 'linkage'), sep = '_') %>% 
      sapply(function(x) str_remove(x,'\\%'))
    return(data)
  }) %>%
  mutate(across(everything(), ~ {
    converted <- suppressWarnings(as.numeric(.))
    if (all(is.na(converted)) && !all(is.na(.))) . else converted
  }))
```

```{r echo=FALSE}
full.table <- data %>% 
  filter(method != 'asm-fcs-kraken2-smalldb',
         (method == 'asm-fcs-kraken2' & tool == 'kraken')|
         (method == 'asm-kraken2-fcs' & tool == 'fcs')|
         (method == 'kraken2-asm-fcs' & tool == 'fcs')) %>% 
  split(.$Linkage)
```

# Compleasm and QUAST results

## eukaryota_odb10

```{r echo=FALSE}
full.table$eukaryota_odb10 %>% 
  mutate(across(`# contigs (>= 0 bp)`:`# N's per 100 kbp`, scales::label_comma())) %>%
  mutate(across(-c(sample, confidence.score, method, data.base), ~ paste0(cur_column(), ":", .))) %>% 
  unite(metric, 'S', 'D', 'F','M','N', 'Total length', '# contigs', 'N50','L50', sep = '<br>') %>% 
  mutate(method = str_c(data.base, method, sep = '\n')) %>% 
  arrange(method) %>% 
  select(metric, sample, method, confidence.score) %>% 
  group_by(sample) %>% 
  pivot_wider(names_from = method, values_from = metric) %>% arrange(confidence.score) %>% 
  gt %>% 
  fmt_markdown(columns = everything())
```

## stramenopiles_odb10

```{r echo=FALSE}
full.table$stramenopiles_odb10 %>% 
  mutate(across(`# contigs (>= 0 bp)`:`# N's per 100 kbp`, scales::label_comma())) %>%
  mutate(across(-c(sample, confidence.score, method, data.base), ~ paste0(cur_column(), ":", .))) %>% 
  unite(metric, 'S', 'D', 'F','M','N', 'Total length', '# contigs', 'N50','L50', sep = '<br>') %>% 
  mutate(method = str_c(data.base, method, sep = '\n')) %>% 
  arrange(method) %>% 
  select(metric, sample, method, confidence.score) %>% 
  group_by(sample) %>% 
  pivot_wider(names_from = method, values_from = metric) %>% arrange(confidence.score) %>% 
  gt %>% 
  fmt_markdown(columns = everything())
```

## performance using small Kraken2 database

```{r echo=FALSE}
smalldb <- data %>% 
  filter(method == 'asm-fcs-kraken2-smalldb'& tool == 'kraken' |
         method == 'asm-fcs-kraken2'& tool == 'kraken', 
         data.base == 'oomycota-genomic',
         confidence.score == 0.5) %>% 
  split(.$Linkage)
```

```{r echo=FALSE}
smalldb$eukaryota_odb10 %>% 
  mutate(across(`# contigs (>= 0 bp)`:`# N's per 100 kbp`, scales::label_comma())) %>%
  mutate(across(-c(sample, confidence.score, method, data.base), ~ paste0(cur_column(), ":", .))) %>% 
  unite(metric, 'S', 'D', 'F','M','N', 'Total length', '# contigs', 'N50','L50', sep = '<br>') %>% 
  select(metric, sample, method, confidence.score) %>% 
  group_by(sample) %>% 
  pivot_wider(names_from = method, values_from = metric) %>% arrange(confidence.score) %>% 
  gt %>% 
  fmt_markdown(columns = everything())

```


```{r echo=FALSE}
smalldb$stramenopiles_odb10 %>% 
  mutate(across(`# contigs (>= 0 bp)`:`# N's per 100 kbp`, scales::label_comma())) %>%
  mutate(across(-c(sample, confidence.score, method, data.base), ~ paste0(cur_column(), ":", .))) %>% 
  unite(metric, 'S', 'D', 'F','M','N', 'Total length', '# contigs', 'N50','L50', sep = '<br>') %>% 
  select(metric, sample, method, confidence.score) %>% 
  group_by(sample) %>% 
  pivot_wider(names_from = method, values_from = metric) %>% arrange(confidence.score) %>% 
  gt %>% 
  fmt_markdown(columns = everything())

```