---
title: "Scaffolds"
output:
  html_document: default
---

```{r message=FALSE, echo=FALSE}
library(Biostrings)
library(tidyverse)
library(pctax)
library(pcutils)
library(gt)
library(here)
```

# mitochondria

threshold: alignment length >= 3000

```{r echo=FALSE}
blast.tb <- list.files('~/project_data/downy/BLAST',
                       pattern = '.mito.tsv', full.names = TRUE) |> 
  map_dfr(function(file) {
    read.table(file, colClasses = c('character')) |> mutate(sample = str_remove(basename(file), '.mito.tsv'))
  })
blast <- blast.tb |>
  transmute(
    sample = sample,
    seqid = V1,
    pident = V3,
    align.length = V4,
    query.length = V5,
    subject.length = V6,
    e.value = V7
  ) |>
  mutate(across(-c(sample, seqid), \(x) type.convert(x, as.is = TRUE))) |> 
  mutate(`align/query` = round(align.length/query.length, 3))

mito.scaffold <- blast |> 
  filter(str_detect(seqid, 'RagTag'), align.length >= 3000) |> 
  group_by(sample) |> 
  arrange(desc(align.length), desc(pident), .by_group = TRUE)
mito.scaffold |> 
  gt() 
```

# Extract mitochondrial scaffolds

```{r}
library(Biostrings)
files <- list.files('~/project_data/downy/Scaffold/', recursive = TRUE, full.names = TRUE, pattern = '.fasta.gz')
for (file in files) {
  data <- readDNAStringSet(file)
  contigs <- mito.scaffold |> 
    filter(sample == str_remove(basename(file),'.fasta.gz'))
  writeXStringSet(data[contigs$seqid], here('data', 'mito_scaffold', str_remove(basename(file),'.gz')))
}
```

# Extract unplaced contigs

```{r}
files <- list.files('~/project_data/downy/Scaffold/', recursive = TRUE, full.names = TRUE, pattern = '.fasta.gz')
for (file in files) {
  data <- readDNAStringSet(file)
  contigs <- names(data)[!str_detect(names(data), 'RagTag')]
  writeXStringSet(data[contigs], here('data', 'unplaced_contigs', str_remove(basename(file),'.gz')))
}
```

blast unplaced contigs with mito.scaffolds

```{bash eval=FALSE}
blastn -query ./data/unplaced_contigs/Quesada_SQIIe_MSU1.fasta \
  -subject ./data/mito_scaffold/Quesada_SQIIe_MSU1.fasta \
  -outfmt "6 qseqid sseqid pident length qlen slen evalue" \
  -max_target_seqs 1 \
  -max_hsps 1 \
  -out ./data/mito_scaffold/Quesada_SQIIe_MSU1.tsv
  
blastn -query ./data/unplaced_contigs/Quesada_SQIIe_Phumuli.fasta \
  -subject ./data/mito_scaffold/Quesada_SQIIe_Phumuli.fasta \
  -outfmt "6 qseqid sseqid pident length qlen slen evalue" \
  -max_target_seqs 1 \
  -max_hsps 1 \
  -out ./data/mito_scaffold/Quesada_SQIIe_Phumuli.tsv
  
blastn -query ./data/unplaced_contigs/Quesada_SQIIe_SC1982.fasta \
  -subject ./data/mito_scaffold/Quesada_SQIIe_SC1982.fasta \
  -outfmt "6 qseqid sseqid pident length qlen slen evalue" \
  -max_target_seqs 1 \
  -max_hsps 1 \
  -out ./data/mito_scaffold/Quesada_SQIIe_SC1982.tsv
```

Map contigs to mito scaffolds.

```{r echo=FALSE}
blast.tb <- list.files('../data/mito_scaffold',
                       pattern = '.tsv', full.names = TRUE) |> 
  map_dfr(function(file) {
    read.table(file, colClasses = c('character')) |> mutate(sample = str_remove(basename(file), '.mito.tsv'))
  })
blast <- blast.tb |>
  transmute(
    sample = sample,
    seqid = V1,
    subid = V2,
    pident = V3,
    align.length = V4,
    query.length = V5,
    subject.length = V6,
    e.value = V7
  ) |>
  mutate(across(-c(sample, seqid), \(x) type.convert(x, as.is = TRUE))) |> 
  mutate(`align/query` = round(align.length/query.length, 3))

mito.scaffold <- blast |> 
  group_by(sample) |> 
  arrange(desc(`align/query`), desc(align.length), .by_group = TRUE)
mito.scaffold |> 
  gt() 
```



# BLAST nt/nr

threshold: alignment length >= 3000

```{r echo=FALSE}
blast.tb <- list.files('~/project_data/downy/BLAST',
                       pattern = '.nt.tsv', full.names = TRUE) |> 
  map_dfr(function(file) {
    read.table(file, colClasses = c('character')) |> mutate(sample = str_remove(basename(file), '.nt.tsv'))
  })

blast <- blast.tb |>
  transmute(
    sample = sample,
    seqid = V1,
    pident = V3,
    align.length = V4,
    query.length = V5,
    subject.length = V6,
    e.value = V7,
    name_or_id2df(blast.tb$V8,mode = 'id',fill_miss_rank = FALSE,add_prefix = FALSE) |> select(Phylum, Species)) |>
  mutate(across(-c(sample, seqid), \(x) type.convert(x, as.is = TRUE))) |> 
  mutate(`align/query` = round(align.length/query.length, 3))

blast |> 
  filter(str_detect(seqid, 'RagTag'), align.length >= 3000) |> 
  group_by(sample, seqid) |> 
  arrange(desc(`align/query`), desc(align.length), .by_group = TRUE) |> 
  gt() 
```