---
title: "synteny-analysis"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(GENESPACE)
```

```{r  message=FALSE, echo=FALSE, results=FALSE}
genomeRepo <- "~/project_data/downy/genespace-scaffold/genomes"
wd <- "~/project_data/downy/genespace-scaffold"
path2mcscanx <- "/home5/yyang55/miniforge3/bin"
folders <- list.dirs(genomeRepo, recursive = FALSE, full.names = FALSE)
# all folder except c("Quesada_SQIIe_SC1982", "Quesada_SQIIe_MSU1", "Quesada_SQIIe_Phumuli")
genomes2run <- folders[!folders %in% c("Quesada_SQIIe_SC1982", "Quesada_SQIIe_MSU1", "Quesada_SQIIe_Phumuli", "Peronospora_effusa_reassemble", "Phytophthora_agathidicida")]
parsedPaths <- parse_annotations(
  rawGenomeRepo = genomeRepo,
  genomeDirs = genomes2run,
  genomeIDs = genomes2run,
  headerSep = NA,
  headerEntryIndex = 1,
  genespaceWd = wd)
asm2run <- c("Quesada_SQIIe_SC1982", "Quesada_SQIIe_MSU1", "Quesada_SQIIe_Phumuli", "Peronospora_effusa_reassemble")
parsedPaths <- parse_annotations(
  rawGenomeRepo = genomeRepo,
  genomeDirs = c(asm2run, "Phytophthora_agathidicida"),
  genomeIDs = c(asm2run, "Phytophthora_agathidicida"),
  headerSep = NA,
  headerEntryIndex = 1,
  gffIdColumn = "ID",
  genespaceWd = wd)

gpar <- init_genespace(
  wd = wd,
  nCores = 32,
  dotplots = 'never',
  path2mcscanx = path2mcscanx)

out <- run_genespace(gpar)
```

# Riparian

```{r echo=FALSE}
genome.order <- c("Peronospora_effusa", "Peronospora_effusa_reassemble",
                  "Quesada_SQIIe_MSU1", "Quesada_SQIIe_SC1982", "Quesada_SQIIe_Phumuli")
full.plot <- plot_riparian(
  gsParam = out,
  genomeIDs = genome.order,
  chrLabFun = function(x) "",
  refGenome = "Peronospora_effusa",
  useRegions = FALSE)
```

```{r echo=FALSE}
genome.order <- c("Peronospora_effusa", 
                  "Peronospora_effusa_reassemble",
                  "Quesada_SQIIe_MSU1", 
                  "Quesada_SQIIe_SC1982", 
                  "Quesada_SQIIe_Phumuli",
                  "Phytophthora_agathidicida",
                  "Phytophthora_infestans",
                  "Plasmopara_halstedii",
                  "Bremia_lactucae",
                  "Phytophthora_sojae"
                  )
full.plot <- plot_riparian(
  gsParam = out,
  genomeIDs = rev(genome.order),
  refGenome = "Peronospora_effusa",
  #chrLabFontSize = 2,
  chrLabFun = function(x) "",
  useRegions = FALSE)
```



```{r echo=FALSE}
# library(ggtree)
# library(ggplot2)
# library(patchwork)
# 
# tree.path <- file.path(wd, 'results/SpeciesTree_rooted.txt')
# tree <- ggtree(read.tree(tree.path))
# tree_data <- tree$data
# tip_data <- tree_data[tree_data$isTip, ]
# species_order <- tip_data$label[order(tip_data$y)]
# num_species <- length(species_order)
# 
# # make sure both figure using same limits
# y_limits <- c(0.5, num_species + 0.5)
# aligned_tree <- tree +
#   scale_y_continuous(limits = y_limits, expand = c(0, 0)) +
#   theme(plot.margin = margin(t = 10, r = 0, b = 10, l = 10))
# 
# aligned_synteny <- full.plot$plotData$ggplotObj +
#   scale_y_continuous(
#     limits = y_limits, 
#     expand = c(0, 0),
#     breaks = 1:num_species,
#     labels = species_order) +
#   ylab(NULL) +
#   theme(
#     plot.margin = margin(t = 10, r = 10, b = 10, l = 0),
#     axis.text.y = element_text(color = "black") 
#   )
# 
# aligned_tree + aligned_synteny + plot_layout(widths = c(1, 4))
```

```{r echo=FALSE}
# library(ape)
# library(tidytree)
# library(ggplot2)
# library(patchwork)
# 
# # Read the tree
# tree.path <- file.path(wd, 'results/SpeciesTree_rooted.txt')
# phylo_tree <- read.tree(tree.path)
# 
# # Get species order from tree (tip order from bottom to top)
# species_order <- phylo_tree$tip.label[order.dendrogram(as.dendrogram(phylo_tree))]
# num_species <- length(species_order)
# y_limits <- c(0.5, num_species + 0.5)
# 
# # Alternative: Create a simple tree representation for ggplot
# tree_df <- data.frame(
#   species = factor(species_order, levels = species_order),
#   x = 0,
#   y = 1:num_species
# )
# 
# # Simple tree-like plot in ggplot
# tree_plot <- ggplot(tree_df, aes(x = x, y = y)) +
#   geom_text(aes(label = species), hjust = 1, size = 3) +
#   xlim(-0.5, 0.5) +
#   scale_y_continuous(limits = y_limits, expand = c(0, 0)) +
#   theme_void() +
#   theme(plot.margin = margin(t = 10, r = 0, b = 10, l = 10))
# 
# # Your synteny plot (this should work as-is)
# aligned_synteny <- full.plot$plotData$ggplotObj +
#   scale_y_continuous(
#     limits = y_limits, 
#     expand = c(0, 0),
#     breaks = 1:num_species,
#     labels = species_order
#   ) +
#   ylab(NULL) +
#   theme(
#     plot.margin = margin(t = 10, r = 10, b = 10, l = 0),
#     axis.text.y = element_text(color = "black") 
#   )
# 
# # Combine plots
# tree_plot + aligned_synteny + plot_layout(widths = c(1, 4))
```

