---
title: "synteny-analysis"
output: html_document
---

```{r echo=FALSE, message=FALSE}
library(GENESPACE)
library(ape)
library(here)
```

```{r  message=FALSE, echo=FALSE, results=FALSE, eval=FALSE}
genomeRepo <- "~/project_data/downy/genespace-contigs/genomes"
wd <- "~/project_data/downy/genespace-contigs"
path2mcscanx <- "~/miniforge3/bin"
asm2run <- list.dirs(genomeRepo, recursive = FALSE, full.names = FALSE)

parsedPaths <- parse_annotations(
  rawGenomeRepo = genomeRepo,
  genomeDirs = asm2run,
  genomeIDs = asm2run |> stringr::str_replace('-','_'),
  headerSep = NA,
  headerEntryIndex = 1,
  gffIdColumn = "ID",
  genespaceWd = wd)

gpar <- init_genespace(
  wd = wd,
  nCores = 32,
  dotplots = 'never',
  path2mcscanx = path2mcscanx)

out <- run_genespace(gpar)
saveRDS(out, here('data', 'genespace.rds'))

tree.path <- file.path(wd, 'results/SpeciesTree_rooted.txt')
tr <- read.tree(tree.path)
saveRDS(tr, here('data', 'tree.rds'))
```


```{r echo=FALSE}
out <- readRDS(here('data', 'genespace.rds'))
genome.order <- c("Phytophthora_infestans_1306", 
                  "Plasmopara_halstedii_710",
                  "Bremia_lactucae_SF5",
                  "Phytophthora_capsici_BYA5",
                  "Phytophthora_plurivora_TJ71",
                  "Peronospora_effusa_UA202013",
                  "Peronospora_effusa_reassemble",
                  "Pseudoperonospora_cubensis_MSU1", 
                  "Pseudoperonospora_cubensis_SC1982", 
                  "Pseudoperonospora_humuli_OR502AA",
                  "Pythium_oligandrum_PO_1",
                  "Phytophthora_ramorum_Pr_102",
                  "Phytophthora_sojae_JS2",
                  "Phytophthora_agathidicida_3770",
                  "Peronospora_destructor_Pd_K2019"
                  )
full.plot <- plot_riparian(
  gsParam = out,
  genomeIDs = rev(genome.order),
  refGenome = "Peronospora_effusa_UA202013",
  #chrLabFontSize = 2,
  chrLabFun = function(x) "",
  useRegions = FALSE)
```





```{r}
library(ggtree)
library(ggplot2)
library(patchwork)

tr <- readRDS(here('data','tree.rds'))
tree <- ggtree(tr)

# rotate Peronospora clade so that destructor is on top
peronospora_node <- getMRCA(
  tr,
  c("Peronospora_effusa_reassemble",
    "Peronospora_effusa_UA202013",
    "Peronospora_destructor_Pd_K2019")
)

tree <- ggtree::rotate(tree, peronospora_node)

tree_data <- tree$data
tip_data <- tree_data[tree_data$isTip, ]

# important: order tips by actual plotting y position, from top to bottom
tip_data <- tip_data[order(tip_data$y, decreasing = TRUE), ]

# make sure both figures use same limits
y_limits <- c(0.5, length(tip_data$label) + 0.5)

aligned_tree <- tree + 
  scale_y_continuous(limits = y_limits, expand = c(0, 0)) +
  theme(plot.margin = margin(t = 10, r = 0, b = 10, l = 10))

full.plot <- plot_riparian(
  gsParam = out,
  genomeIDs = rev(tip_data$label),
  refGenome = "Peronospora_effusa_UA202013",
  chrLabFun = function(x) "",
  useRegions = FALSE
)

aligned_synteny <- full.plot$plotData$ggplotObj +
  scale_y_continuous(
    limits = y_limits,
    expand = c(0, 0),
    breaks = 1:length(tip_data$label),
    labels = rev(tip_data$label)
  ) +
  ylab(NULL) +
  theme(
    plot.margin = margin(t = 10, r = 10, b = 10, l = 0),
    axis.text.y = element_text(color = "black")
  )

aligned_tree + aligned_synteny + plot_layout(widths = c(1, 4))
```

```{r}
library(tidyverse)
ortho.groups <- read.table(list.files(wd, pattern = 'Orthogroups.GeneCount.tsv', full.names = TRUE, recursive = TRUE),
                           header = TRUE, sep = '\t', stringsAsFactors = FALSE) 

ortho.groups.sub <- ortho.groups |> 
  select("Orthogroup", "Pseudoperonospora_cubensis_MSU1", "Pseudoperonospora_cubensis_SC1982", "Pseudoperonospora_humuli_OR502AA") |> 
  # filter(
  #   Pseudoperonospora_cubensis_SC1982 >= 2 |
  #   Pseudoperonospora_cubensis_MSU1 >= 2 |
  #   Pseudoperonospora_humuli_OR502AA >= 2
  # ) |> 
  pivot_longer(cols = -Orthogroup, names_to = "sample", values_to = "count")
# 
# ggplot(ortho.groups.sub) +
#   geom_col(aes(x = Orthogroup, y = count, group = sample, color = sample, fill = sample), position = "dodge") +
#   theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())  

```

```{r}
ortho.groups.sub |>
  group_by(sample) |>
  summarise(
    mean_copy = mean(count),
    median_copy = median(count),
    `prop_copy>2` = mean(count >= 2),
    max_copy = max(count)
  ) |> gt::gt()
```


